### ISSUE TITLE
add_path not found centerlines with Trim Iterations set 

### ISSUE THREAD

**Issue by dorinoltean** [BjornNyberg/Geometric-Attributes-Toolbox#10]
I have qgis 3.18.3 on one computer where centerlines works fine.
And qgis 3.20.0 on another computer where i get ` 'Graph' object has no attribute 'add_path'`

On computer qgis 3.18.3 i have `networkx==2.2` 
On computer qgis 3.20.0 i have `networkx==2.5.1`  - 

> QGIS version: 3.20.0-Odense
> QGIS code revision: decaadbb31
> Qt version: 5.15.2
> Python version: 3.9.5
> GDAL version: 3.3.0
> GEOS version: 3.9.1-CAPI-1.14.2
> PROJ version: Rel. 8.0.1, March 5th, 2021
> PDAL version: 2.3.0 (git-version: eac774)
> Processing algorithm…
> Algorithm 'Centerlines' starting…
> Input parameters:
> { 'Centerlines' : 'TEMPORARY_OUTPUT', 'Densify Field' : '', 'Line Spacing' : 0, 'Method' : 0, 'Polygons' : 'C:/Users/dorin/work/nice/roads.shp', 'Simplify' : 0, 'Simplify Field' : '', 'Trim Field' : '', 'Trim Iterations' : 2 }
> 
> Creating Vertices
> Creating Voronoi Polygons
> Calculating Edges
> Results: {'OUTPUT': 'output_ffc7cca8_7da0_4fb9_82a5_33f29040c09d'}
> Results: {'OUTPUT': 'output_3cf847bf_6789_48e8_8d28_bfa76eda21fe'}
> Calculating 1 Centerlines
> 'Graph' object has no attribute 'add_path'
> No centerline found for polygon ID 0 - skipping
> Execution completed in 12.28 seconds
> Results:
> {'Centerlines': 'Centerlines_675ec218_663b_40ea_ac7e_5043d16cb977'}
> 
> Loading resulting layers
> Algorithm 'Centerlines' finished

**Comment by BjornNyberg** [comment]
@dorinoltean it would appear that Networkx have updated the API slighlty but I believe the issue is now solved. 

Please reinstall the plugin and let me know.

**Comment by dorinoltean** [comment]
thanks. after installing the plugin from source code it works.
