### ISSUE TITLE
saga:thiessenpolygons tool not available

### ISSUE THREAD

**Issue by stepanosokin** [BjornNyberg/Geometric-Attributes-Toolbox#13]
Hi! Thank You so much for your perfect plugin! 
Had a smll issue when running Centerline tool in QGIS 3.22. Got the error:
_saga:thiessenpolygons tool not available_
Managed to cope with that by replacing _saga:thiessenpolygons_ with  _sagang:thiessenpolygons_ in the source code. Probably, the tool name had changed.

**Comment by BjornNyberg** [comment]
Hi @stepanosokin 

Many thanks for that information. Ive updated the plugin accordingly.

**Comment by poabbey** [comment]
Hello! Echoing @stepanosokin, thank you so much for this awesome plugin! It looks like the name of the thiessenpolygons tool changed again as I'm getting the error "Error: Algorithm sagang:thiessenpolygons not found" when trying to run the "Centerlines" tool. Do you know how I can find the new name of the tool?

Cheers

**Comment by poabbey** [comment]
Nevermind, I just found out that QGIS 3.30 doesn't include SAGA anymore! I just had to install the "Processing Saga NextGen Provider" plugin and the Centerlines tool works again. Sorry to bother!
