### ISSUE TITLE
Python uncompatibility for SAM

### ISSUE THREAD

**Issue by cycle4** [BjornNyberg/Geometric-Attributes-Toolbox#15]
Hello !
Thank you for the development of this useful tool !
My issue happens with the SAM model. The error I get when I try to run the segmentation process with the right checkpoint paths and a valid image is the following : 

![image](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/assets/120014072/5763d614-9c29-4a2a-8fef-a984b48ef2a8)

As you can see, even if Python 3.10 is the one used by QGIS  (3.28 is the last ltr so should not need any update), the error says that I should have a Python version over 3.8... which is the case. 

I also had problems when running the configuration, but managed to go around by installing the checkpoints by myself, and by running the command os.system('pip install segment-geospatial') in the Python console of QGIS to be able to import samgeo.
I still get this error after running the configuration process : 
![image](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/assets/120014072/b861b832-babb-4c20-9f92-44dbb60bfe7a)

Can you help me with that please ? Feel free to ask for more details if needed !

I am working on Ubuntu 22.04.2LTS

**Comment by BjornNyberg** [comment]
Hi @cycle4 

Did you manage to solve the issue? I havent personally tested with Ubuntu but if you remove these [lines](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/blob/7642e1f4d880d552138260fb3dba6e7116dc4b7f/geometric_attributes/SAM.py#L168) does it solve the problem?
Alternatively, if you open the python console within QGIS and type: 

`import sys`
`print(sys.version[:3])`

what message do you receive? Perhaps a better way to implement this check if anyone has a suggestion.

**Comment by BjornNyberg** [comment]
@cycle4 

I think the problem is solved now. Please reinstall the plugin from the plugin manager and let me know if your issue is resolved.

**Comment by cycle4** [comment]
Hello @BjornNyberg 
Thank you for your answer !
Yes it seems to work now even without removing the line specifying the version in the Python file you attached. 
I now have a problem of memory allocation with Pythorch, but I was able to solve it when running SAM directly on Python so it should not be a problem
Thanks again !
