### ISSUE TITLE
Cannot generate the Width Parameter in Attribute Table

### ISSUE THREAD

**Issue by muhammadbagushari** [BjornNyberg/Geometric-Attributes-Toolbox#20]
Hi, Bjorn.

I want ask about the width parameter (line that is perpendicular with a centreline) after creating centreline. In my case, I want to know the width parameter in my attribute table, but I do not know why the width parameter is not generated.
Can you tell me what should I do?
I hereby attach the screenshot of the attribute table of centreline layer.
![image](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/assets/121832236/03d80228-de4a-4174-89fc-6453521a0c56)

**Comment by muhammadbagushari** [comment]
I try to use 'Geometric Attributes' in Polygon Tools to generate the width parameter, but unfortunately it does not succeed, and there is a warning as I attach below.
![image](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/assets/121832236/440552b4-dcf1-42c8-9908-859581c3ee46)

And this is the attribute table of my river polygon
![image](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/assets/121832236/7e32ea31-9f33-4a15-8c3b-0742e76897e1)

On the other hand, this is the attribute tables of centreline
![image](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/assets/121832236/34dccbdd-02f7-46dc-99e4-9c2cd1c2bc0a)

What should I do to fix this problem?

**Comment by BjornNyberg** [comment]
Hi @muhammadbagushari 

The ID field is case sensitive.  Delete the 'id' and create a new 'ID' field. 

Regarding the previous question - the geometric attributed will create width measurements. If you want the width measurements on the centerline, you will need to join the data!

**Comment by muhammadbagushari** [comment]
Thank you for the response.
case is closed.
