### ISSUE TITLE
SAM error in QGIS: save the vector layer as a geopackage (.gpkg) file.

### ISSUE THREAD

**Issue by sonalij1901** [BjornNyberg/Geometric-Attributes-Toolbox#23]
Hi @BjornNyberg  , I installed the samgeo python package in QGIS, on trying to configure the SAM tool, I get the following error:
![Screen Shot 2024-03-06 at 11 15 07 AM](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/assets/162491010/497e25d1-f411-4306-8d6b-0549fbd2620c)

I've manually downloaded the checkpoint files and placed them in the correct folder. When I try to run the tool with Landsat data, I get the following error:
![Screen Shot 2024-03-06 at 11 10 28 AM](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/assets/162491010/4931b9ca-1286-4fff-86b3-4c8feb988458)

Is there a way to make this work? I've tried converting the layer to gpkg but it still gives me the same error.

Thanks in advance for your help!

**Comment by BjornNyberg** [comment]
Hi @sonalij1901 Did you try to save the polygons file as a geopackage file?
