### ISSUE TITLE
Error --> Algorithm sagang:thiessenpolygons not found

### ISSUE THREAD

**Issue by robbitt** [BjornNyberg/Geometric-Attributes-Toolbox#24]
Running Centerlines on any polygon vector gives and error --> Algorithm sagang:thiessenpolygons not found

QGIS version: 3.36.2-Maidenhead
QGIS code revision: 6d250527
Qt version: 5.15.13
Python version: 3.12.3
GDAL version: 3.8.5
GEOS version: 3.12.1-CAPI-1.18.1
PROJ version: Rel. 9.4.0, March 1st, 2024
PDAL version: 2.6.3 (git-version: 816ce1)
Algorithm started at: 2024-05-21T11:25:17
Algorithm 'Centerlines' starting…
Input parameters:
{ 'Centerlines' : 'TEMPORARY_OUTPUT', 'Densify Field' : '', 'Line Spacing' : 0, 'Method' : 0, 'Polygons' : 'E:/_DOCS/Projects_Robs_working/Side_Channel_GIS/_Kapusta Island/GIS/GIS_asbuilts.gpkg|layername=impact_polygons_post', 'Simplify' : 0, 'Simplify Field' : '', 'Trim Field' : '', 'Trim Iterations' : 0 }

Creating Vertices
Creating Voronoi Polygons
Error: Algorithm sagang:thiessenpolygons not found

Execution failed after 0.10 seconds

**Comment by RyeDK** [comment]
I too am having this issue.

**Comment by BjornNyberg** [comment]
Hi @robbitt and @RyeDK Have you checked that the SAGA tools are enabled as explained here? https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/wiki/FAQ

See also - https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/issues/13

**Comment by RyeDK** [comment]
I updated QGIS from 3.3 to 3.4 and had activate GRASS 8 as it was using GRASSS 7 before updating and the centerline function now runs, Thanks. However it does not perform well on my geometry, perhaps it is too complex for this function.

**Comment by BjornNyberg** [comment]
@RyeDK Great that you got the tool working. For complex polygons make sure to use the 'densify vertex spacing' option - although this will increase the processing time. More info is available in the user guide https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/wiki/User-Guide

**Comment by RyeDK** [comment]
@BjornNyberg With some simple cleaning of my data and tuning of the parameters as you mentioned, it is working great, thanks!
