### ISSUE TITLE
Run “Centerlines”，提示找不着（can't find）sagang:thiessenpolygons

### ISSUE THREAD

**Issue by iuuunlyk** [BjornNyberg/Geometric-Attributes-Toolbox#26]
Creating Vertices
Creating Voronoi Polygons
**错误：找不到算法sagang:thiessenpolygons**
Execution failed after 0.56 秒

加载结果图层
算法“Centerlines”执行已完成

QGIS 3.34 On Mac

**Comment by BjornNyberg** [comment]
Hi @iuuunlyk 

Have you tried to follow the install instructions here - https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/wiki/FAQ ?
