### ISSUE TITLE
Dependency missing

### ISSUE THREAD

**Issue by giapoldo** [BjornNyberg/Geometric-Attributes-Toolbox#4]
QGIS says networkx is missing and to "fix manually". I've checked my QGIS install and networkx is present. It also imports without issue on the python console.

**Comment by BjornNyberg** [comment]
Thanks, QGIS includes networkx as standard in its python version so this dependency is not needed.

**Comment by giapoldo** [comment]
Thanks for the reply, how do I use the plugin if it gives me this warning though? Should I wait for an update?

Thanks again!

**Comment by BjornNyberg** [comment]
Hi Garvamel,


Can you please send a screenshot and maybe I can assess the issue as I dont plan on releasing an update any time soon.


Cheers,

Bjorn

________________________________

**Comment by giapoldo** [comment]
I just reinstalled it for the warning to pop up and now it didn't, and it shows up on the toolbox, miracle? Haha. Thanks though!

**Comment by AbelVM** [comment]
Missing `networkx` and `scipy` in 3.12 QGIS :(

**Comment by BjornNyberg** [comment]
@AbelVM Are you on a Mac OS? In that case you will need to install networkx and scipy manually to your python interpreter.

**Comment by AbelVM** [comment]
Ubuntu 18.04.1 here

I manually installed both libraries and now it works, but it should take care of the dependencies on install, isn't it?

**Comment by BjornNyberg** [comment]
@AbelVM As far as im aware - QGIS will only warn that dependencies are missing but will not install libraries to ensure that it will not automatically break the python dependencies that QGIS or your other plugins require.
