### ISSUE TITLE
Problems with centerline generation using networkx 2.4

### ISSUE THREAD

**Issue by suricactus** [BjornNyberg/Geometric-Attributes-Toolbox#6]
I have tried to use your plugin to generate centerlines, but I have encountered several errors. I am using Ubuntu 20.04q which is an LTS version and it is expected that quite a lot of users (will) use it too. There is an `networkx` API that has deprecated and removed from 2.4:

`networkx.connected_component_subgraphs(G)`

AFAIK it can be replaced with:

```
def connected_component_subgraphs(G):
	for c in nx.connected_components(G):
    	yield G.subgraph(c)
```

However, this does not solve all the issues:
```
Traceback (most recent call last):
File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geometric_attributes/Centerlines.py", line 469, in processAlgorithm
G.clear()
File "/usr/lib/python3/dist-packages/networkx/classes/function.py", line 144, in frozen
raise nx.NetworkXError("Frozen graph can't be modified")
networkx.exception.NetworkXError: Frozen graph can't be modified
```

I have managed to produce centerlines in another way, so I didn't dig deeper into issues.

**Comment by BjornNyberg** [comment]
Thanks @suricactus 

Im glad that you found a solution. Nonetheless I think I've managed to solve the issue.
