### ISSUE TITLE
Centerlines output error

### ISSUE THREAD

**Issue by limw10** [BjornNyberg/Geometric-Attributes-Toolbox#9]
![Road](https://user-images.githubusercontent.com/71323054/98903844-794f2f80-250c-11eb-896e-281d25bc7b29.JPG)
![Centerlines](https://user-images.githubusercontent.com/71323054/98903896-94ba3a80-250c-11eb-8ce9-dcc638d3fa01.JPG)

Hi there, i have tried the functionality of the plugin in QGIS on my road polygon layer but it doesnt seem to be generating all the centerlines. I have buffered the polygon to -0.1 as recommended to avoid any over lap and test with various line spacing parameters but still end up with an incomplete centerlines. see images for reference. Your assistance will be greatly appreciated!

**Comment by limw10** [comment]
![Centerlines2](https://user-images.githubusercontent.com/71323054/98905123-fd0a1b80-250e-11eb-8cc9-d3b43bb86dc5.JPG)
Hi again, just following up, I adjusted the parameters for Densify Vertex Spacing, the results is better but still i am not getting the complete centerlines. Thanks

**Comment by BjornNyberg** [comment]
@linw10 Did you solve the problem? I would be able to help more if I could recieve a sample dataset to test in order to reproduce the problem. Nonetheless I can see that you need to use a trim iterations option rather than "All". All option will define all centerlines from one startpoint to one endpoint. Whereas trim iterations will be able to find multiple endpoints.

**Comment by BjornNyberg** [comment]
As an example take a look at this road network from London for clarification. This dataset is from OSM and contains one dissolve polygon representing roads. In this example trim iterations were set at 10 but will vary depending on the complexity of your polygon (i.e. how many vertices will define a new branch). 

![Centerlines](https://user-images.githubusercontent.com/37108459/99538930-ee5bb280-29ad-11eb-9dcf-21569c57c4ea.jpg)
![All](https://user-images.githubusercontent.com/37108459/99538965-f6b3ed80-29ad-11eb-86db-f16b6977fd81.jpg)
![Trim](https://user-images.githubusercontent.com/37108459/99539290-55796700-29ae-11eb-8177-336cf327be69.jpg)

**Comment by limw10** [comment]
@BjornNyberg , thanks for the illustration over here, it helps alot. I got the plugin work out in the end. There is no issues with it. Thanks alot and a great plugin tool!
